313DEVGRP/Java-Service-Tree-Framework-Engine-Fire

- settings.gradle
- src/main/java/com/Application.java
- src/main/resources/application.yml
프로젝트 이름 및 포트 설정 - 23.07.27
#close #time 5m +review SR @313devops
[NoSql Index] …
> chore: [JIRA-1] #comment

- src/main/java/com/arms/cloud/jiraissuetypescheme/controller/CloudJiraIssueTypeSchemeController.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/domain/CloudJiraIssueTypeSchemeMappingDTO.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/domain/CloudJiraIssueTypeSchemeMappingValueDTO.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/domain/IssueTypeIdsDTO.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/service/CloudJiraIssueTypeScheme.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/service/CloudJiraIssueTypeSchemeImpl.java
- src/test/java/com/arms/cloud/CloudJiraIssueTypeSchemeTest.java
> feat: [JAVA-1] #comment 요구사항 IssueType이 없는 IssueTypeScheme에 추가하도록 하는 컨트롤러 및 기능 추가 - 23.07.29

- src/main/java/com/arms/cloud/jiraissue/controller/CloudJiraIssueController.java
- src/main/java/com/arms/cloud/jiraissue/domain/CloudJiraIssueDTO.java
- src/main/java/com/arms/cloud/jiraissue/domain/CloudJiraIssueInputDTO.java
- src/main/java/com/arms/cloud/jiraissue/domain/CloudJiraIssueSearchDTO.java
- src/main/java/com/arms/cloud/jiraissue/domain/FieldsDTO.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssue.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssueImpl.java
이슈 생성 및 조회 DTO 정리 - 23.07.30
[NoSql Index] …
> refactor: [JIRA-3] #comment

- src/test/java/com/arms/cloud/CloudJiraIssueTest.java
- src/test/java/com/arms/cloud/CloudJiraIssueTypeSchemeTest.java
- src/test/java/com/arms/cloud/CloudJiraIssueTypeTest.java
- src/test/java/com/arms/cloud/CloudJiraProjectTest.java
1. issue type 생성 테스트 코드 추가
2. 프로젝트 별 이슈 타입 전체 조회 테스트 코드 추가
3. 매핑된 이슈 타입 스킴 조회 파라미터 maxResults 값으로 숫자 넘어갈 시 페이징 처리 관련 처리 테스트 코드 수정 - 23.07.30
[DB Admin] …
> test: [JAVA-1] #comment

- build.gradle
- src/main/java/com/arms/cloud/jiraissuetype/controller/CloudJiraIssueTypeController.java
- src/main/java/com/arms/cloud/jiraissuetype/dao/CloudJiraIssueTypeJpaRepository.java
- src/main/java/com/arms/cloud/jiraissuetype/domain/CloudJiraIssueTypeEntity.java
- src/main/java/com/arms/cloud/jiraissuetype/service/CloudJiraIssueType.java
- src/main/java/com/arms/cloud/jiraissuetype/service/CloudJiraIssueTypeImpl.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/service/CloudJiraIssueTypeScheme.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/service/CloudJiraIssueTypeSchemeImpl.java
- src/main/java/com/arms/config/CloudJiraConfig.java
- src/main/resources/application.yml
- src/test/java/com/arms/cloud/CloudJiraIssueTest.java
- src/test/java/com/arms/cloud/CloudJiraIssueTypeSchemeTest.java
- src/test/java/com/arms/cloud/CloudJiraIssueTypeTest.java
- src/test/java/com/arms/cloud/CloudJiraProjectTest.java
1. issue type  생성 후 DB 저장
2. issue type shceme 스케줄러 실행 시 '요구사항' 이슈 타입 아이디 DB 정보로 교체
3. 테스트 코드 내용 수정 - 23.07.31 #close #time 1h +review SR @313devops
[S3 Admin] …
> feat: [JAVA-1] #comment  로컬 DB 연결, 저장

- src/main/java/com/arms/cloud/jiraissue/dao/CloudJiraIssueJpaRepository.java
- src/main/java/com/arms/cloud/jiraissue/domain/CloudJiraIssueEntity.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/main/java/com/arms/cloud/jiraissuetype/service/CloudJiraIssueTypeImpl.java
1. 이슈 생성 시 이슈 아이디, 키, url timestamp DB 저장 timestamp는 DB 삽입 시점 기록
2. createIssueType, createIssue 메서드에 트랜션 어노테이션 추가- 23.08.01 #close #time 1h +review SR @313devops …
> feat: [JIRA-1] #comment 이슈 생성시 DB 저장

- src/main/java/com/arms/cloud/jiraissue/domain/CloudJiraIssueEntity.java
- src/main/java/com/arms/cloud/jiraissue/domain/FieldsDTO.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/main/java/com/arms/cloud/jiraissuetype/domain/CloudJiraIssueTypeDTO.java
- src/main/java/com/arms/cloud/jiraissuetype/service/CloudJiraIssueTypeImpl.java
- src/test/java/com/arms/cloud/CloudJiraIssueTest.java
- src/test/java/com/arms/cloud/CloudJiraIssueTypeTest.java
1. 이슈 조회(link, subtask) 로직 테스크 코드
2. IssueLink, Subtask 공통 필드 사용으로 CloudJiraIssueDTO로 변경
3. 코드 규격 리팩토링
[S3 Admin] …
> test, refactor: [JIRA-1] #comment 이슈 조회(link, subtask) 로직 테스크 코드 - 23.08.01

- src/main/java/com/arms/cloud/jiraconnectinfo/dao/CloudJiraConnectInfoJpaRepository.java
- src/main/java/com/arms/cloud/jiraconnectinfo/domain/CloudJiraConnectInfoDTO.java
- src/main/java/com/arms/cloud/jiraconnectinfo/domain/CloudJiraConnectInfoEntity.java
- src/main/java/com/arms/cloud/jiraconnectinfo/service/CloudJiraConnectInfo.java
- src/main/java/com/arms/cloud/jiraconnectinfo/service/CloudJiraConnectInfoImpl.java
- src/main/java/com/arms/config/CloudJiraConfig.java
- src/main/resources/application.yml
- src/test/java/com/arms/cloud/CloudJiraConnectInfoTest.java
Test 코드 및 CloudjiraConfig, application.yml 데이터 정리
[MEM Admin] …
> feat: [JIRA-1] #comment WebClient 빈 생성 시 DB에서 Cloud Jira Coonnection 정보 가져오도록 변경 - 23.08.01

- src/main/java/com/arms/cloud/jiraissue/controller/CloudJiraIssueController.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssue.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssueImpl.java
1. 이슈 삭제 처리시 서브테스크 까지 자동 삭제 로직 및 에러 메세지 생성 로직 추가
2. 이슈 삭제시 이슈 테이블 조회후 삭제 처리- 23.08.02 #close #time 1h +review SR @313devops
[S3 Admin] …
> feat: [JIRA-2] #comment 이슈 삭제 처리

- src/main/java/com/arms/errors/CommonResponse.java
- src/main/java/com/arms/errors/response/ErrorCode.java
- src/main/java/com/arms/errors/response/ErrorControllerAdvice.java
> feat: [JAVA-1] #comment ControllerAdvice 이용하여 API 호출 오류 시 Error 처리  - 23.08.02

- src/main/java/com/arms/cloud/jiraissue/controller/CloudJiraIssueController.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssue.java
- src/main/java/com/arms/cloud/jiraissue/service/CloudJiraIssueImpl.java
이슈 수정 기능 추가 - 23.08.04
[NoSql Index] …
> feat: [JIRA-5] #comment

- src/main/java/com/arms/cloud/CloudJiraUtils.java
- src/main/java/com/arms/cloud/jiraconnectinfo/dao/CloudJiraConnectInfoJpaRepository.java
- src/main/java/com/arms/cloud/jiraconnectinfo/domain/CloudJiraConnectInfoEntity.java
- src/main/java/com/arms/cloud/jiraconnectinfo/service/CloudJiraConnectInfoImpl.java
- src/main/java/com/arms/cloud/jiraissuetype/controller/CloudJiraIssueTypeController.java
- src/main/java/com/arms/cloud/jiraissuetype/service/CloudJiraIssueTypeImpl.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/controller/CloudJiraIssueTypeSchemeController.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/service/CloudJiraIssueTypeScheme.java
- src/main/java/com/arms/cloud/jiraissuetypescheme/service/CloudJiraIssueTypeSchemeImpl.java
- src/main/java/com/arms/cloud/jiraproject/service/CloudJiraProject.java
- src/main/java/com/arms/cloud/jiraproject/service/CloudJiraProjectImpl.java
- src/main/java/com/arms/config/CloudJiraConfig.java
- src/main/resources/application.yml
> style: [JAVA-1] #comment 코드 스타일 수정, 사용하지 않는 내용 정리 - 23.08.04

- src/main/java/com/engine/jira/cloud/jiraissue/controller/CloudJiraIssueController.java
- src/main/java/com/engine/jira/cloud/jiraissue/model/CloudJiraIssueEntity.java
- src/main/java/com/engine/jira/cloud/jiraissue/model/CloudJiraIssuePK.java
- src/main/java/com/engine/jira/cloud/jiraissue/service/CloudJiraIssue.java
- src/main/java/com/engine/jira/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/main/java/com/engine/jira/onpremise/JiraUtils.java
- src/main/java/com/engine/jira/onpremise/issuetype/service/OnPremiseJiraIssueType.java
- src/main/java/com/engine/jira/onpremise/issuetype/service/OnPremiseJiraIssueTypeImpl.java
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::Advanc2d ]
[NoSql Index] …
> feat: [ENGINE-1] #comment Jira Issue Link, Subtas 수집 후 DB 저장 기능 추가(재설계 필요) 및 Onpremise 관련 사항 내용 추가 - 23.08.07

- src/main/java/com/arms/jira/onpremise/jiraissue/controller/OnPremiseJiraIssueController.java
- src/main/java/com/arms/jira/onpremise/jiraissue/dao/OnPremiseJiraIssueJpaRepository.java
- src/main/java/com/arms/jira/onpremise/jiraissue/model/FieldsDTO.java
- src/main/java/com/arms/jira/onpremise/jiraissue/model/OnPremiseJiraIssueDTO.java
- src/main/java/com/arms/jira/onpremise/jiraissue/model/OnPremiseJiraIssueEntity.java
- src/main/java/com/arms/jira/onpremise/jiraissue/model/OnPremiseJiraIssueInputDTO.java
- src/main/java/com/arms/jira/onpremise/jiraissue/model/OnPremiseJiraIssuePK.java
- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssue.java
- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssueImpl.java
- src/main/java/com/arms/jira/onpremise/jiraproject/service/OnPremiseOnPremiseJiraProjectImpl.java
온프레미스 이슈 생성 기능 추가 - 23.08.09
[NoSql Index] …
> feat: [JIRA-8] #comment

- build.gradle
- src/main/java/com/arms/jira/onpremise/jiraissue/controller/OnPremiseJiraIssueController.java
- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssue.java
- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssueImpl.java
이슈 전체 조회시 이슈 갯수가 maxResults를 넘을때 표시 못하는 데이터 처리23.08.10 #close #time 1h +review SR @313devops
[MEM Admin] …
> feat: [ONPREMISE-2] #comment 이슈 전체 조회 기능 수정

- src/main/java/com/arms/jira/onpremise/jirapriority/controller/OnPremiseJiraPriorityController.java
- src/main/java/com/arms/jira/onpremise/jirapriority/service/OnPremiseJiraPriority.java
- src/main/java/com/arms/jira/onpremise/jirapriority/service/OnPremiseJiraPriorityImpl.java
- src/main/java/com/arms/jira/onpremise/jiraresolution/controller/OnPremiseJiraResolutionController.java
- src/main/java/com/arms/jira/onpremise/jiraresolution/service/OnPremiseJiraResolution.java
- src/main/java/com/arms/jira/onpremise/jiraresolution/service/OnPremiseJiraResolutionImpl.java
1. 온프레미스 우선순위 리스트 조회
2. 온프레미스 해결책 리스트 조회 #close #time 1h +review SR @313devops …
> feat: [JIRA-10] #comment 온프레미스 조회 API 추가 - 23.08.15

- src/main/java/com/arms/jira/onpremise/jirastatus/controller/OnPremiseJiraStatusController.java
- src/main/java/com/arms/jira/onpremise/jirastatus/service/OnPremiseJiraStatus.java
- src/main/java/com/arms/jira/onpremise/jirastatus/service/OnPremiseJiraStatusImpl.java
이슈 상태리스트  조회 기능 추가 23.08.15
[NoSql Index] …
> feat: [ONPREMISE-3] #comment 이슈 상태 리스트 API 추가

- src/main/java/com/arms/jira/onpremise/jirapriority/controller/OnPremiseJiraPriorityController.java
- src/main/java/com/arms/jira/onpremise/jirapriority/model/OnPremiseJiraPriorityDTO.java
- src/main/java/com/arms/jira/onpremise/jirapriority/service/OnPremiseJiraPriority.java
- src/main/java/com/arms/jira/onpremise/jirapriority/service/OnPremiseJiraPriorityImpl.java
- src/main/java/com/arms/jira/onpremise/jiraresolution/controller/OnPremiseJiraResolutionController.java
- src/main/java/com/arms/jira/onpremise/jiraresolution/model/OnPremiseJiraResolutionDTO.java
- src/main/java/com/arms/jira/onpremise/jiraresolution/service/OnPremiseJiraResolution.java
- src/main/java/com/arms/jira/onpremise/jiraresolution/service/OnPremiseJiraResolutionImpl.java
1. 온프레미스 우선순위 리스트 DTO 처리
2. 온프레미스 해결책 리스트 DTO 처리 #close #time 1h +review SR @313devops
[MEM Admin] …
> refactor: [JIRA-11] #comment 온프레미스 조회 API DTO 처리 - 23.08.15

- src/main/java/com/arms/jira/onpremise/jirastatus/controller/OnPremiseJiraStatusController.java
- src/main/java/com/arms/jira/onpremise/jirastatus/model/OnPremiseJiraStatusDTO.java
- src/main/java/com/arms/jira/onpremise/jirastatus/service/OnPremiseJiraStatus.java
- src/main/java/com/arms/jira/onpremise/jirastatus/service/OnPremiseJiraStatusImpl.java
이슈 상태리스트  DTO 전환 23.08.15
[NoSql Index] …
> feat: [ONPREMISE-4] #comment 이슈 상태 리스트 DTO 추가

- src/main/java/com/arms/jira/onpremise/jirastatus/model/OnPremiseJiraStatusDTO.java
- src/main/java/com/arms/jira/onpremise/jirastatus/service/OnPremiseJiraStatusImpl.java
이슈 상태리스트  DTO id String으로 변경처리 23.08.15 …
> feat: [ONPREMISE-4] #comment 이슈 상태 리스트 DTO 수정

- src/main/java/com/arms/jira/cloud/jiraissue/controller/CloudJiraIssueController.java
- src/main/java/com/arms/jira/cloud/jiraissue/model/FieldsDTO.java
- src/main/java/com/arms/jira/cloud/jiraissue/service/CloudJiraIssue.java
- src/main/java/com/arms/jira/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuepriority/controller/CloudJiraIssuePriorityController.java
- src/main/java/com/arms/jira/cloud/jiraissuepriority/model/Priority.java
- src/main/java/com/arms/jira/cloud/jiraissuepriority/model/PrioritySearchDTO.java
- src/main/java/com/arms/jira/cloud/jiraissuepriority/service/CloudJiraIssuePriority.java
- src/main/java/com/arms/jira/cloud/jiraissuepriority/service/CloudJiraIssuePriorityImpl.java
- src/main/java/com/arms/jira/cloud/jiraissueresolution/controller/CloudJiraIssueResolutionController.java
- src/main/java/com/arms/jira/cloud/jiraissueresolution/model/Resolution.java
- src/main/java/com/arms/jira/cloud/jiraissueresolution/model/ResolutionSearchDTO.java
- src/main/java/com/arms/jira/cloud/jiraissueresolution/service/CloudJiraIssueResolution.java
- src/main/java/com/arms/jira/cloud/jiraissueresolution/service/CloudJiraIssueResolutionImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuestatus/controller/CloudJiraIssueStatusController.java
- src/main/java/com/arms/jira/cloud/jiraissuestatus/model/Status.java
- src/main/java/com/arms/jira/cloud/jiraissuestatus/model/StatusSearchDTO.java
- src/main/java/com/arms/jira/cloud/jiraissuestatus/service/CloudJiraIssueStatus.java
- src/main/java/com/arms/jira/cloud/jiraissuestatus/service/CloudJiraIssueStatusImpl.java
- src/test/java/com/engine/jira/cloud/CloudJiraIssueTest.java
1. Priority List Api 패키지 이동
2. Resolution  List Api 패키지 이동
3. Status  List Api 추가 …
> feat: [ENGINE-4] #comment

- src/main/java/com/arms/config/ElasticsearchClientConfig.java
- src/main/java/com/arms/jira/cloud/jiraissuetype/service/CloudJiraIssueTypeImpl.java
1. ElasticsearchClientConfig.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. @SuppressWarnings("deprecation") 경고 처리
2. CloudJiraIssueTypeImpl.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. NullPointException 부분 주석 처리
- 23.08.16
[CodeAnalysis] …
> feat: [ENGINE-5] #comment 컴파일 오류 처리

- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssueImpl.java
1. 이슈 라벨 업데이트시 오류 처리
2. 요약 설명 라벨 이외의 다른 값 업데이트 시도시 오류 처리 추가
3. Request json 오류처리 추가 23.08.16 #close #time 1h +review SR @313devops
[S3 Admin] …
> feat: [ONPREMISE-5] #comment 이슈 업데이트 수정

- src/main/java/com/arms/jira/cloud/jiraissue/dao/CloudJiraIssueJpaRepository.java
- src/main/java/com/arms/jira/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/main/java/com/arms/jira/cloud/jiraproject/controller/CloudJiraProjectController.java
- src/test/java/com/engine/jira/cloud/CloudJiraIssueTest.java
- src/test/java/com/engine/jira/onpremise/OnPremiseJiraIssueTest.java
1. Cloud Issue Label 추가 메소드 생성(API로 갈지 말지 판단 필요)
2. Cloud Issue 스케줄러 확인 중 오류 -> 해결(JPA Query Entity 값이 OnPremise로 설정)
3. 변수명 리팩토링
4. 테스트 코드 추가
- 23.08.17
[DB Admin] …
> feat, refactor: [ENGINE-5] #comment

- src/main/java/com/arms/jira/cloud/jiraissuetype/service/CloudJiraIssueTypeImpl.java
- src/test/java/com/engine/jira/cloud/scheduler/SchedulerIssueTest.java
1. Cloud Issue Type List 형태로 변환 시 DTO 없는 값 반영으로 ParameterizedTypeReference로 변경 처리
2. 스케줄러 테스트 코드 추가
- 23.08.17
[S3 Admin] …
> refactor: [ENGINE-6] #comment

- src/main/java/com/arms/errors/response/ErrorControllerAdvice.java
- src/main/java/com/arms/jira/info/service/EsJiraInfoImpl.java
- src/main/java/com/arms/jira/info/service/JiraInfo.java
- src/main/java/com/arms/jira/info/service/JiraInfoImpl.java
- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssue.java
- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssueImpl.java
- src/main/java/com/arms/jira/onpremise/jiraissuepriority/service/OnPremiseJiraIssuePriorityImpl.java
- src/main/java/com/arms/jira/onpremise/jiraissueresolution/service/OnPremiseJiraIssueResolutionImpl.java
- src/main/java/com/arms/jira/onpremise/jiraissuestatus/service/OnPremiseJiraIssueStatusImpl.java
- src/main/java/com/arms/jira/onpremise/jiraissuetype/service/OnPremiseJiraIssueTypeImpl.java
- src/main/java/com/arms/jira/onpremise/jiraproject/service/OnPremiseOnPremiseJiraProjectImpl.java
1.  connectId null값으로 들어올 시 전역 오류 메세지 처리
2.  connection 정보 조회 메서드 생성하여 validation 처리  23.08.19
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::chanho470 ]
[S3 Admin] …
> feat: [ONPREMISE-7] #comment connection 관련 오류 메세지 처리

- src/main/java/com/arms/jira/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/test/java/com/engine/jira/cloud/scheduler/CloudIssueSchedulerTest.java
- src/test/java/com/engine/jira/onpremise/scheduler/OnPremiseIssueSchedulerTest.java
1. Cloud Issue Subtask, Inward Link 조회
2. OnPremise Issue Subtask, Inward Link 조회 …
> test: [ENGINE-5] #comment Issue Subtask, Inward Link 스케줄러 Test Code - 23.08.18

- src/main/java/com/arms/jira/info/model/JiraInfoDTO.java
- src/main/java/com/arms/jira/info/model/JiraInfoEntity.java
- src/main/java/com/arms/jira/jiraproject/controller/지라_프로젝트_컨트롤러.java
- src/main/java/com/arms/jira/jiraproject/model/지라_프로젝트_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraproject/service/지라_프로젝트_전략_교체.java
- src/main/java/com/arms/jira/jiraproject/strategy/온프라미스_지라_프로젝트_전략.java
- src/main/java/com/arms/jira/jiraproject/strategy/지라_프로젝트_전략.java
- src/main/java/com/arms/jira/jiraproject/strategy/지라_프로젝트_전략_등록_및_실행.java
- src/main/java/com/arms/jira/jiraproject/strategy/클라우드_지라_프로젝트_전략.java
> test: [ENGINE-5] #comment Jira Project Cloud, OnPremise 전략패턴으로 통합, JiraInfoEntity, JiraInfoDTO type 컬럼 추가 - 23.08.20

- src/main/java/com/arms/jira/jiraissueresolution/controller/지라_이슈_해결책_컨트롤러.java
- src/main/java/com/arms/jira/jiraissueresolution/model/지라_이슈_해결책.java
- src/main/java/com/arms/jira/jiraissueresolution/model/클라우드_지라_이슈_해결책_전체_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissueresolution/service/지라_이슈_해결책_전략_교체.java
- src/main/java/com/arms/jira/jiraissueresolution/strategy/온프라미스_지라_이슈_해결책_전략.java
- src/main/java/com/arms/jira/jiraissueresolution/strategy/지라_이슈_해결책_전략.java
- src/main/java/com/arms/jira/jiraissueresolution/strategy/지라_이슈_해결책_전략_등록_및_실행.java
- src/main/java/com/arms/jira/jiraissueresolution/strategy/클라우드_지라_이슈_해결책_전략.java
- src/main/java/com/arms/jira/jiraissuetype/controller/지라_이슈_유형_컨트롤러.java
- src/main/java/com/arms/jira/jiraissuetype/model/지라_이슈_유형_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissuetype/service/지라_이슈_유형_전략_교체.java
- src/main/java/com/arms/jira/jiraissuetype/strategy/온프라미스_지라_이슈_유형_전략.java
- src/main/java/com/arms/jira/jiraissuetype/strategy/지라_이슈_유형_전략.java
- src/main/java/com/arms/jira/jiraissuetype/strategy/지라_이슈_유형_전략_등록_및_실행.java
- src/main/java/com/arms/jira/jiraissuetype/strategy/클라우드_지라_이슈_유형_전략.java
- src/main/java/com/arms/jira/jiraproject/strategy/클라우드_지라_프로젝트_전략.java
> feat: [ENGINE-6] #comment Jira Issue Resolution, Issue Type Cloud, OnPremise 전략패턴으로 통합 - 23.08.20

- src/main/java/com/arms/jira/jiraissuestatus/controller/지라_이슈_상태_컨트롤러.java
- src/main/java/com/arms/jira/jiraissuestatus/model/지라_이슈_상태_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissuestatus/model/클라우드_지라_이슈_상태_전체_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissuestatus/service/지라_이슈_상태_전략_호출.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/온프라미스_지라_이슈_상태_전략.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/지라_이슈_상태_전략.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/지라_이슈_상태_전략_등록_및_실행.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/클라우드_지라_이슈_상태_전략.java
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::chanho470]
[NoSql Index] …
> feat: [ENGINE-7] #comment Jira Issue status 전략패턴으로 통합 - 23.08.20

- src/main/java/com/arms/jira/cloud/jiraproject/controller/CloudJiraProjectController.java
- src/main/java/com/arms/jira/info/service/EsJiraInfoImpl.java
- src/main/java/com/arms/jira/info/service/JiraInfoImpl.java
- src/main/java/com/arms/jira/onpremise/jiraissue/controller/OnPremiseJiraIssueController.java
> refactor: [ENGINE-6] #comment Jira Server 등록 시 오류 해결 - 23.08.20

- src/main/java/com/arms/jira/info/model/지라_유형_정보.java
- src/main/java/com/arms/jira/jiraissue/controller/지라_이슈_컨트롤러.java
- src/main/java/com/arms/jira/jiraissue/model/지라_이슈_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissue/model/지라_이슈_생성_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissue/service/지라_이슈_전략_호출.java
- src/main/java/com/arms/jira/jiraissue/strategy/온프레미스_지라_이슈_전략.java
- src/main/java/com/arms/jira/jiraissue/strategy/지라_이슈_전략.java
- src/main/java/com/arms/jira/jiraissue/strategy/지라_이슈_전략_등록_및_실행.java
- src/main/java/com/arms/jira/jiraissue/strategy/클라우드_지라_이슈_전략.java
- src/main/java/com/arms/jira/jiraissueresolution/service/지라_이슈_해결책_전략_호출.java
- src/main/java/com/arms/jira/jiraissueresolution/strategy/온프레미스_지라_이슈_해결책_전략.java
- src/main/java/com/arms/jira/jiraissuestatus/service/지라_이슈_상태_전략_호출.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/온프레미스_지라_이슈_상태_전략.java
- src/main/java/com/arms/jira/jiraissuetype/model/지라_이슈_유형_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissuetype/service/지라_이슈_유형_전략_호출.java
- src/main/java/com/arms/jira/jiraissuetype/strategy/온프레미스_지라_이슈_유형_전략.java
- src/main/java/com/arms/jira/jirapriority/model/지라_이슈_우선순위_데이터_전송_객체.java
- src/main/java/com/arms/jira/jirapriority/service/지라_이슈_우선순위_전략_호출.java
- src/main/java/com/arms/jira/jirapriority/strategy/온프레미스_지라_이슈_우선순위_전략.java
- src/main/java/com/arms/jira/jiraproject/service/지라_프로젝트_전략_호출.java
- src/main/java/com/arms/jira/jiraproject/strategy/온프레미스_지라_프로젝트_전략.java
1. Jira Issue Cloud, OnPremise 전략패턴 배경작업 완료 Cloud, OnPremise 구현부 작업 진행 필요
2. 온프라미스 => 온프레미스로 변경
3. ENUM 지라_유형_정보 사용하여 전략 패턴 스위칭 작업
[DB Admin] …
> feat: [ENGINE] #comment Jira Issue Cloud, OnPremise 전략패턴 배경작업 완료 - 23.08.20

- src/main/java/com/arms/jira/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuepriority/service/CloudJiraIssuePriorityImpl.java
- src/main/java/com/arms/jira/cloud/jiraissueresolution/service/CloudJiraIssueResolutionImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuestatus/service/CloudJiraIssueStatusImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuetype/service/CloudJiraIssueTypeImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuetypescheme/service/CloudJiraIssueTypeSchemeImpl.java
- src/main/java/com/arms/jira/cloud/jiraproject/service/CloudJiraProjectImpl.java
- src/main/java/com/arms/jira/jiraissue/controller/지라_이슈_컨트롤러.java
- src/main/java/com/arms/jira/jiraissue/service/지라_이슈_전략_호출.java
- src/main/java/com/arms/jira/jiraissue/strategy/온프레미스_지라_이슈_전략.java
- src/main/java/com/arms/jira/jiraissue/strategy/지라_이슈_전략.java
- src/main/java/com/arms/jira/jiraissue/strategy/지라_이슈_전략_등록_및_실행.java
- src/main/java/com/arms/jira/jiraissue/strategy/클라우드_지라_이슈_전략.java
- src/main/java/com/arms/jira/jiraissueresolution/service/지라_이슈_해결책_전략_호출.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/클라우드_지라_이슈_상태_전략.java
- src/main/java/com/arms/jira/jiraproject/strategy/클라우드_지라_프로젝트_전략.java
- src/test/java/com/engine/jira/cloud/CloudJiraConnectInfoTest.java
loadConnect -> checkInfo로 변경(null 오류 처리 포함 메소드)
[MEM Admin] …
> :see_no_evil: feat: [ENGINE] #comment 이슈 삭제 라벨 처리 API 추가 - 23.08.23

- src/main/java/com/arms/jira/jiraissue/model/클라우드_지라_이슈_필드_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissue/strategy/클라우드_지라_이슈_전략.java
클라우드 이슈 생성 시, 사용자 정보를 조회하여 보고자, 담당자 정보를 설정 …
> :boom: refactor: [JIRA-20] #comment 보고자, 담당자 설정 - 23.08.24

- src/main/java/com/arms/jira/jiraissue/model/클라우드_지라_이슈_조회_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissue/strategy/클라우드_지라_이슈_전략.java
> :alien:feat: [ENGINE] #comment 이슈조회, 프로젝트 하위 이슈 전체조회 클라우드 추가 - 23.08.24

- src/main/java/com/arms/jira/info/service/JiraInfoImpl.java
> :boom: refactor: [JIRA-21] #comment 오타 수정 - 23.08.27

- src/main/java/com/arms/jira/cloud/CloudJiraUtils.java
- src/main/java/com/arms/jira/cloud/jiraissue/service/CloudJiraIssueImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuepriority/service/CloudJiraIssuePriorityImpl.java
- src/main/java/com/arms/jira/cloud/jiraissueresolution/service/CloudJiraIssueResolutionImpl.java
- src/main/java/com/arms/jira/cloud/jiraissuestatus/service/CloudJiraIssueStatusImpl.java
- src/main/java/com/arms/jira/jiraissue/model/지라_이슈_데이터_전송_객체.java
- src/main/java/com/arms/jira/jiraissueresolution/strategy/클라우드_지라_이슈_해결책_전략.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/클라우드_지라_이슈_상태_전략.java
- src/main/java/com/arms/jira/jirapriority/strategy/클라우드_지라_이슈_우선순위_전략.java
- src/main/java/com/arms/jira/onpremise/jiraissue/service/OnPremiseJiraIssueImpl.java
- src/test/java/com/engine/jira/cloud/CloudJiraIssueTest.java
- src/test/java/com/engine/jira/cloud/CloudJiraIssueTypeSchemeTest.java
- src/test/java/com/engine/jira/onpremise/OnPremiseJiraIssueTest.java
- src/test/java/com/engine/jira/onpremise/scheduler/OnPremiseIssueSchedulerTest.java
WebClient DataBuffer를 이용하여 Buffer Exception 관련 Test 코드 추가
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::Advanc2d ]
[MEM Admin] …
> :see_no_evil: refactor: [ENGINE] #comment 페이징 처리를 위해 maxResult 50으로 통일 - 23.08.27

- src/main/java/com/arms/jira/jiraissue/strategy/온프레미스_지라이슈_전략.java
id, key, self 필드 set
[NoSql Index] …
> :boom: refactor: [JIRA-24] #comment 온프레미스 이슈 조회 시 누락된 필드 set - 23.08.31

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_서비스.java
- src/main/resources/application-live.yml
*** 필드부분 ELK DTO에 내용 추가 필요 ***
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::Advanc2d ]
[NoSql …
> :see_no_evil: feat: [ENGINE] #comment 지라 이슈, 링크드 이슈, 서브테스크 가져온 후 ELK DTO 데이터 변환 후 ELK 벌크 저장 완료 - 23.08.30

- src/main/java/com/arms/elasticsearch/models/지라이슈.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
조회 후 데이터 변환하여 ELK에 벌크로 저장
[NoSql Index] …
> :see_no_evil: feat: [ENGINE] #comment 지라 이슈, 링크드 이슈, 서브테스크 저장 Entity 내용 추가 - 23.08.31

- src/main/java/com/arms/elasticsearch/models/지라이슈.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
지라 version은 관리 대상이 아니므로 삭제
[ Backend-Core::Java-Service-Tree-Framework(JSTF)::Advanc2d ]
[NoSql Index] …
> :see_no_evil: refactor: [ENGINE] #comment ELK 지라이슈 Entity fixVersions 삭제 - 23.08.31

- src/main/java/com/arms/elasticsearch/models/지라이슈.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/jira/jiraissue/model/지라이슈필드_데이터.java
- src/main/java/com/arms/jira/jiraissue/strategy/온프레미스_지라이슈_전략.java
- src/main/resources/application-dev.yml
- src/main/resources/application-live.yml
- src/test/java/com/arms/jira/jiraissue/service/통합이슈조회테스트.java
- src/test/java/com/engine/jira/cloud/CloudJiraIssueTest.java
에러코드 시 404관련 오류 사항 문제로 yml 정보 주석 
[NoSql …
> :see_no_evil: refactor: [ENGINE] #comment Summary 추가 및 fixVersions 삭제 - 23.09.01

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/models/지라이슈.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_서비스.java
pdServiceName -> pdServiceId로 변경 Long 타입, pdServiceVersion Long 타입으로 변경
[MEM …
> :see_no_evil: refactor: [ENGINE] #comment pdServiceName -> pdServiceId로 변경, pdServiceVersion Long으로 변경 - 23.09.03

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_서비스.java
1. 전체 상태별 집계
2. 프로젝트별 상태 집계
[NoSql Index] …
> :ailen:  feat: [ENGINE] #comment 상태 집계 - 23.09.03

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
삭제된 이슈와 링크드이슈, 서브테스크 status "해당 요구사항은 지라서버에서 조회가 되지 않는 상태입니다." 문구로 변경 처리
[MEM …
> :see_no_evil: refactor: [ENGINE] #comment 삭제된 이슈와 링크드이슈, 서브테스크 status 변경 처리 - 23.09.03

- src/main/java/com/arms/serverinfo/controller/서버정보_컨트롤러.java
- src/main/java/com/arms/serverinfo/model/서버정보_데이터.java
- src/main/java/com/arms/serverinfo/repositories/서버정보_저장소.java
- src/main/java/com/arms/serverinfo/service/서버정보_서비스.java
- src/main/java/com/arms/serverinfo/service/서버정보_서비스_구현.java
삭제관련 기능은 차후 설계 후 개발 진행 예정으로 코드 주석처리
[NoSql …
> :see_no_evil: refactor: [ENGINE] #comment 서버정보 수정 가능하도록 변경(서버 등록과 같은 API) - 23.09.05

- src/main/java/com/arms/serverinfo/service/서버정보_서비스_구현.java
> :see_no_evil: refactor: [ENGINE] #comment 삭제관련 기능은 차후 설계 후 개발 진행 예정으로 코드 주석처리 - 23.09.05

- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/errors/exception/전역오류처리.java
- src/main/java/com/arms/jira/jiraissue/strategy/온프레미스_지라이슈_전략.java
- src/main/java/com/arms/jira/jiraissue/strategy/클라우드_지라이슈_전략.java
- src/main/java/com/arms/jira/jiraissuestatus/controller/지라이슈상태_컨트롤러.java
- src/main/java/com/arms/jira/jiraissuestatus/service/지라이슈상태_전략_호출.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/지라이슈상태_전략_등록_및_실행.java
- src/main/java/com/arms/jira/jiraissuestatus/strategy/클라우드_지라이슈상태_전략.java
- src/main/java/com/arms/jira/jiraissuetype/strategy/온프레미스_지라이슈유형_전략.java
- src/main/java/com/arms/jira/jiraissuetype/strategy/클라우드_지라이슈유형_전략.java
- src/main/java/com/arms/jira/jirapriority/strategy/온프레미스_지라이슈우선순위_전략.java
- src/main/java/com/arms/jira/jirapriority/strategy/클라우드_지라이슈우선순위_전략.java
- src/main/java/com/arms/jira/jiraproject/strategy/온프레미스_지라프로젝트_전략.java
- src/main/java/com/arms/jira/jiraproject/strategy/클라우드_지라프로젝트_전략.java
> :see_no_evil: refactor: [ENGINE] #comment 사용하지 않는 클래스 제거 및 코드 포맷 정리 - 23.09.05

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_서비스.java
> :see_no_evil: refactor: [ENGINE] #comment ELK 이슈 저장 관련 테스트 코드, 데이터 -> 저장기능으로 변경 - 23.09.05

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_서비스.java
> :ailen: feat: [ENGINE] #comment 하위이슈 할당자 빈도수 집계 - 23.09.07

- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
> :alien: refactor: [ENGINE] #comment 제품 서비스 별 하위 이슈 담당자 통계  - 23.09.07

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/models/지라이슈.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_서비스.java
- src/main/java/com/arms/errors/exception/전역오류처리.java
- src/main/java/com/arms/jira/jiraissue/model/지라이슈필드_데이터.java
- src/main/java/com/arms/jira/jiraissue/strategy/온프레미스_지라이슈_전략.java
- src/main/java/com/arms/jira/jiraissue/strategy/클라우드_지라이슈_전략.java
기존 DTO updated 필드 추가, Data Set 부분 추가
코드포맷 변경
[MEM Admin] …
> :see_no_evil: feat: [ENGINE] #comment 제품 서비스별 수정일 - 생성일 차이 계산 API 추가 - 23.09.10

- src/main/java/com/arms/elasticsearch/controllers/엘라스틱_지라이슈_컨트롤러.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_검색엔진.java
- src/main/java/com/arms/elasticsearch/services/지라이슈_서비스.java
- src/main/resources/application-live.yml
제품서비스별_담당자_통계 이슈키 넣지 않도록 수정
[NoSql Index] …
> :see_no_evil: refactor: [ENGINE] #comment live 클라우드 api 호출 시 updated 가져오도록 추가 - 23.09.10

- src/main/java/com/arms/elasticsearch/models/지라이슈.java
Nested 사용 시 해당 부분은 Index 따로 적용 필요
제품서비스별_담당자_통계 이슈키 넣지 않도록 수정
[MEM Admin] …
> :see_no_evil: refactor: [ENGINE] #comment @Fields Nested 부분 전체 주석 - 23.09.10

- src/main/java/com/arms/api/engine/dtos/히트맵날짜데이터.java
- src/main/java/com/arms/api/engine/services/지라이슈_검색엔진.java
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::ssoohyun ] 요구 관리 : [Requirement Manage] http://www.a-rms.net
클러스터2 : [DockerSwarm] http://www.313.co.kr/portainer/#!/auth
디비 관리 : [DB Admin] …
> :boom: refactor: [Engine] #comment 일정 분석 히트맵 리턴 데이터 수정 - 23.12.11

- src/main/java/com/arms/api/engine/models/지라이슈_일자별_제품_및_제품버전_검색요청.java
- src/main/java/com/arms/api/engine/services/지라이슈_검색엔진_대시보드.java
> :see_no_evil: refactor: [ENGINE] #comment API 변경으로 검색요청 필드 및 호출부 수정 - 23.12.17

- src/main/java/com/arms/elasticsearch/util/repository/공통저장소_구현체.java
> :see_no_evil: refactor: [ENGINE] #comment 빌드 Unstable 상태 - 23.12.21

- src/main/java/com/arms/api/engine/services/지라이슈_검색엔진.java
- src/main/java/com/arms/api/serverinfo/service/서버정보_서비스_구현.java
- src/main/java/com/arms/elasticsearch/helper/인덱스_유틸.java
RestHighLevelClient 사용 소스 변경 작업
[NoSql …
> :see_no_evil: refactor: [ENGINE] #comment 빌드 인덱스_유틸.java 리팩토링- 23.12.21

- src/main/java/com/arms/api/engine/controllers/엘라스틱_지라이슈_대시보드_컨트롤러.java
- src/main/java/com/arms/api/engine/dtos/TaskList.java
- src/main/java/com/arms/api/engine/dtos/Worker.java
- src/main/java/com/arms/api/engine/services/지라이슈_검색엔진_대시보드.java
- src/main/java/com/arms/api/engine/services/지라이슈_대시보드_서비스.java
#close #time 3h +review SR @dumbbelloper
See http://www.313.co.kr/jira/browse/ARMS-266 more details.
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::313DEVGRP ] 요구 관리 : [Requirement Manage] http://www.a-rms.net
클러스터2 : [DockerSwarm] …
> feat: [ARMS-266] #comment  트리맵 차트 Echarts -> Jit 변경  - 23.12.23

- src/main/java/com/arms/api/engine/controllers/엘라스틱_지라이슈_대시보드_컨트롤러.java
- src/main/java/com/arms/api/engine/services/지라이슈_검색엔진_대시보드.java
- src/main/java/com/arms/api/engine/services/지라이슈_대시보드_서비스.java
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::ssoohyun ] 요구 관리 : [Requirement Manage] http://www.a-rms.net
클러스터2 : [DockerSwarm] http://www.313.co.kr/portainer/#!/auth
디비 관리 : [DB Admin] …
> :boom: refactor: [Engine] #comment 미사용 endpoint 제거 - 23.12.23

- src/main/java/com/arms/api/engine/services/지라이슈_검색엔진_대시보드.java
> :see_no_evil: refactor: [ENGINE] #comment 기간 검색 소스 리팩토링- 23.12.21

- src/main/java/com/arms/api/engine/controllers/엘라스틱_지라이슈_대시보드_컨트롤러.java
- src/main/java/com/arms/api/engine/dtos/요구사항_별_업데이트_데이터.java
- src/main/java/com/arms/api/engine/services/지라이슈_검색엔진_대시보드.java
- src/main/java/com/arms/api/engine/services/지라이슈_대시보드_서비스.java
- ISSUE 일때 요구사항 기준 연결된 이슈의 업데이트 이력 조회
- REQUIREMENT 일때 요구사항 기준 업데이트 이력 조회 #close #time 1h +review SR @313devops
[MEM …
> :alien: feat: [ENGINE] #comment 등고선 차트를 위한 API 추가 - 23.12.27

- src/main/java/com/arms/api/alm/account/controller/계정_컨트롤러.java
- src/main/java/com/arms/api/alm/account/service/계정전략_호출.java
- src/main/java/com/arms/api/alm/account/strategy/온프레미스_레드마인_계정전략.java
- src/main/java/com/arms/api/alm/account/strategy/온프레미스_지라_계정전략.java
- src/main/java/com/arms/api/alm/account/strategy/클라우드_지라_계정전략.java
- API 수정
- 파라메터 수정
- 에러 구문 수정
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::chanho470 ] 요구 관리 : [Requirement Manage] http://www.a-rms.net
클러스터2 : [DockerSwarm] …
> :alien: refactor: [RedMine#20] #comment 계정 전략- API 수정 - 24.04.01

- src/main/java/com/arms/api/index_entity/서버정보_인덱스.java
- src/main/java/com/arms/api/index_entity/이슈_인덱스.java
- src/main/java/com/arms/api/index_entity/플루언트디_인덱스.java
- src/main/java/com/arms/config/ElasticsearchClientConfig.java
패키지 구조 변경으로 인한 수정
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::Advanc2d ] [Requirement Manage] http://www.a-rms.net
[NoSql Index] …
> :see_no_evil: fix: [Engine] #comment ElasticSearchClientConfig - 24.04.02

- src/main/java/com/arms/api/util/model/enums/IsReqType.java
#close #time 1h +review SR @chanho470
- 백엔드 IsReqType 동기화 ALL인 경우 null 리턴 분기 조건 추가
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::chanho470 ] 요구 관리 : [Requirement Manage] http://www.a-rms.net
클러스터2 : [DockerSwarm] …
> :alien: refactor: [Engine] #comment IsReqType ALL 추가- 24.07.17

- src/main/java/com/arms/api/alm/issue/base/service/jiraissue_schedule/main/이슈_스케쥴_서비스_프로세스.java
- src/main/java/com/arms/api/alm/issue/base/strategy/온프레미스_지라_이슈전략.java
1. 이슈 조회 API 호출 후 오류 발생 시 Exception 발생하여 오류 발생 -> 실패 메세지 반환하도록 반영
2. Sonarqube 대응 - collect(toList()) 반환값 미사용
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::Advanc2d ] [Requirement Manage] http://www.a-rms.net [Document] http://www.313.co.kr/confluence
[S3 Admin] …
>  refactor: [Engine] #comment sonarqube 온프레미스 지라 이슈 상태변경 로직 리팩토링, SonarQube 대응 - 24.08.11

- src/main/java/com/arms/api/alm/issue/status/model/이슈상태_데이터.java
- src/main/java/com/arms/api/alm/issue/status/model/이슈상태_카테고리_데이터.java
1. 상태 카테고리 프리셋 기능 추가를 위한 클라우드 지라 이슈상태 카테고리 데이터 항목 추가
[ Engine-Fire::Java-Service-Tree-Framework(JSTF)::Advanc2d ] [Requirement Manage] http://www.a-rms.net [Document] http://www.313.co.kr/confluence
[MEM Admin] …
> :see_no_evil: feat: [Engine] #comment 클라우드 지라 상태 카테고리 프리셋 기능 - 24.08.28
